name: gestortareas

services:
  backend:
    image: jsnarvaezl/gestortareas-backend:latest
    container_name: gestortareas_backend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PORT: 3000
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "3001:3000"

  frontend:
    image: jsnarvaezl/gestortareas-frontend:latest
    container_name: gestortareas_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8081:80"

volumes:
  uploads_data:
